language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-23
    - android-24
    - android-27
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"
  
