sudo: false
cache: false

language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_EMULATOR_TARGET=android-19

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - $ANDROID_EMULATOR_TARGET
    - extra-google-google_play_services
    - extra-android-support
    - extra
    - sys-img-$ANDROID_ABI-$ANDROID_EMULATOR_TARGET

licenses:
  - 'android-sdk-license-.+'

before_install:
  - echo yes | sdkmanager "platforms;$ANDROID_TARGET" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

script:
  - echo no | android create avd --force -n test -t $ANDROID_EMULATOR_TARGET --abi $ANDROID_ABI --device 'Nexus 4' --sdcard 128M
  - emulator -avd test -no-window &
  - ./gradlew check
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck
