language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - add-on
    - extra
    - sys-img-armeabi-v7a-android-27
    - extra-android-m2repository
    
